version: "3.8"
services:
  db:
    build: ./database/
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  lang_detect_python:
    build: ./lang_detect_python/
    volumes: 
      - ./lang_detect_python/:/usr/src/app/
    ports: 
      - 5001:5001
    environment: 
      PORT: 5001
      FLASK_DEBUG: 1
    # restart: always

  python_app:
    build: ./python_app/
    depends_on:
      - db

  #rust_app:
    #build: ./rust-crawler/
    #depends_on:
      #- db
    #command: --inp_file=file.txt --out_file=out.txt --threads=4 --limit=200

  frontend:
    build: ./website/
    ports:
      - 5000:5000

