version: "3.8"
services:
  # db: # old postgres, should delete probably
  #   build: ./database/
  #   ports:
  #     - 5405:5432
  #   restart: always
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data

  # lang_detect_python:
  #   build: ./lang_detect_python/
  #   volumes: 
  #     - ./lang_detect_python/:/usr/src/app/
  #   ports: 
  #     - 5001:5001
  #   environment: 
  #     PORT: 5001
  #     FLASK_DEBUG: 1
    # restart: always

  # python_app:
  #   build: ./python_app/


  rust_app:
    build: ./rust_crawler/

    command: --inp_file=urls.txt --out_file=out.txt --threads=4 --limit=200

  # frontend:
  #   build: ./website/
  #   ports:
  #     - 5000:5000

  elasticsearch:
    image: "elasticsearch:5"
    networks:
      - frontend # set up a network that we can use across different containers
    restart: always
    healthcheck:  # to prevent apps from quering inexisting database
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./ES_DATA:/usr/share/elasticsearch/data  # where we will store indexed data
    environment:
      - discovery.type=single-node # don't pay attention to these
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"  # port on container->port on host machine
networks:
  frontend: