[package]
name = "site-wasm"
version = "0.1.0"
authors = ["Daria Omelkina <odasha2001@gmail.com>"]
description = "Mini Google web app"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
yew = "0.12"