[package]
name = "website"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
rocket = "0.4.7"

[dependencies.rocket_contrib]
version = "0.4.7"
default-features = false
features = ["handlebars_templates"]
